# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.15.5/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.15.5/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aakash/MastersThesisTUM/2020/boringssl/lsquic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aakash/MastersThesisTUM/2020/boringssl/lsquic

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.15.5/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.15.5/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.15.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aakash/MastersThesisTUM/2020/boringssl/lsquic/CMakeFiles /Users/aakash/MastersThesisTUM/2020/boringssl/lsquic/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aakash/MastersThesisTUM/2020/boringssl/lsquic/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) -f CMakeFiles/docs.dir/build.make CMakeFiles/docs.dir/build
.PHONY : docs/fast

#=============================================================================
# Target rules for targets named http_client

# Build rule for target.
http_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_client
.PHONY : http_client

# fast build rule for target.
http_client/fast:
	$(MAKE) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/build
.PHONY : http_client/fast

#=============================================================================
# Target rules for targets named lsquic

# Build rule for target.
lsquic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lsquic
.PHONY : lsquic

# fast build rule for target.
lsquic/fast:
	$(MAKE) -f src/liblsquic/CMakeFiles/lsquic.dir/build.make src/liblsquic/CMakeFiles/lsquic.dir/build
.PHONY : lsquic/fast

#=============================================================================
# Target rules for targets named test_malo_pooled

# Build rule for target.
test_malo_pooled: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_malo_pooled
.PHONY : test_malo_pooled

# fast build rule for target.
test_malo_pooled/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_malo_pooled.dir/build.make test/unittests/CMakeFiles/test_malo_pooled.dir/build
.PHONY : test_malo_pooled/fast

#=============================================================================
# Target rules for targets named test_min_heap

# Build rule for target.
test_min_heap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_min_heap
.PHONY : test_min_heap

# fast build rule for target.
test_min_heap/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_min_heap.dir/build.make test/unittests/CMakeFiles/test_min_heap.dir/build
.PHONY : test_min_heap/fast

#=============================================================================
# Target rules for targets named test_stream

# Build rule for target.
test_stream: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_stream
.PHONY : test_stream

# fast build rule for target.
test_stream/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_stream.dir/build.make test/unittests/CMakeFiles/test_stream.dir/build
.PHONY : test_stream/fast

#=============================================================================
# Target rules for targets named test_ack_merge

# Build rule for target.
test_ack_merge: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ack_merge
.PHONY : test_ack_merge

# fast build rule for target.
test_ack_merge/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_ack_merge.dir/build.make test/unittests/CMakeFiles/test_ack_merge.dir/build
.PHONY : test_ack_merge/fast

#=============================================================================
# Target rules for targets named test_wuf_gquic_be

# Build rule for target.
test_wuf_gquic_be: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_wuf_gquic_be
.PHONY : test_wuf_gquic_be

# fast build rule for target.
test_wuf_gquic_be/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_wuf_gquic_be.dir/build.make test/unittests/CMakeFiles/test_wuf_gquic_be.dir/build
.PHONY : test_wuf_gquic_be/fast

#=============================================================================
# Target rules for targets named test_ver_nego

# Build rule for target.
test_ver_nego: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ver_nego
.PHONY : test_ver_nego

# fast build rule for target.
test_ver_nego/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_ver_nego.dir/build.make test/unittests/CMakeFiles/test_ver_nego.dir/build
.PHONY : test_ver_nego/fast

#=============================================================================
# Target rules for targets named test_minmax

# Build rule for target.
test_minmax: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_minmax
.PHONY : test_minmax

# fast build rule for target.
test_minmax/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_minmax.dir/build.make test/unittests/CMakeFiles/test_minmax.dir/build
.PHONY : test_minmax/fast

#=============================================================================
# Target rules for targets named test_sfcw

# Build rule for target.
test_sfcw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_sfcw
.PHONY : test_sfcw

# fast build rule for target.
test_sfcw/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_sfcw.dir/build.make test/unittests/CMakeFiles/test_sfcw.dir/build
.PHONY : test_sfcw/fast

#=============================================================================
# Target rules for targets named test_goaway_gquic_be

# Build rule for target.
test_goaway_gquic_be: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_goaway_gquic_be
.PHONY : test_goaway_gquic_be

# fast build rule for target.
test_goaway_gquic_be/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_goaway_gquic_be.dir/build.make test/unittests/CMakeFiles/test_goaway_gquic_be.dir/build
.PHONY : test_goaway_gquic_be/fast

#=============================================================================
# Target rules for targets named test_streamparse

# Build rule for target.
test_streamparse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_streamparse
.PHONY : test_streamparse

# fast build rule for target.
test_streamparse/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_streamparse.dir/build.make test/unittests/CMakeFiles/test_streamparse.dir/build
.PHONY : test_streamparse/fast

#=============================================================================
# Target rules for targets named test_spi

# Build rule for target.
test_spi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_spi
.PHONY : test_spi

# fast build rule for target.
test_spi/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_spi.dir/build.make test/unittests/CMakeFiles/test_spi.dir/build
.PHONY : test_spi/fast

#=============================================================================
# Target rules for targets named test_ackparse_gquic_be

# Build rule for target.
test_ackparse_gquic_be: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ackparse_gquic_be
.PHONY : test_ackparse_gquic_be

# fast build rule for target.
test_ackparse_gquic_be/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_ackparse_gquic_be.dir/build.make test/unittests/CMakeFiles/test_ackparse_gquic_be.dir/build
.PHONY : test_ackparse_gquic_be/fast

#=============================================================================
# Target rules for targets named test_shi

# Build rule for target.
test_shi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_shi
.PHONY : test_shi

# fast build rule for target.
test_shi/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_shi.dir/build.make test/unittests/CMakeFiles/test_shi.dir/build
.PHONY : test_shi/fast

#=============================================================================
# Target rules for targets named test_blocked_gquic_be

# Build rule for target.
test_blocked_gquic_be: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_blocked_gquic_be
.PHONY : test_blocked_gquic_be

# fast build rule for target.
test_blocked_gquic_be/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_blocked_gquic_be.dir/build.make test/unittests/CMakeFiles/test_blocked_gquic_be.dir/build
.PHONY : test_blocked_gquic_be/fast

#=============================================================================
# Target rules for targets named test_stop_waiting_gquic_be

# Build rule for target.
test_stop_waiting_gquic_be: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_stop_waiting_gquic_be
.PHONY : test_stop_waiting_gquic_be

# fast build rule for target.
test_stop_waiting_gquic_be/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_stop_waiting_gquic_be.dir/build.make test/unittests/CMakeFiles/test_stop_waiting_gquic_be.dir/build
.PHONY : test_stop_waiting_gquic_be/fast

#=============================================================================
# Target rules for targets named test_set

# Build rule for target.
test_set: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_set
.PHONY : test_set

# fast build rule for target.
test_set/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_set.dir/build.make test/unittests/CMakeFiles/test_set.dir/build
.PHONY : test_set/fast

#=============================================================================
# Target rules for targets named test_malo_nopool

# Build rule for target.
test_malo_nopool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_malo_nopool
.PHONY : test_malo_nopool

# fast build rule for target.
test_malo_nopool/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_malo_nopool.dir/build.make test/unittests/CMakeFiles/test_malo_nopool.dir/build
.PHONY : test_malo_nopool/fast

#=============================================================================
# Target rules for targets named test_senhist

# Build rule for target.
test_senhist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_senhist
.PHONY : test_senhist

# fast build rule for target.
test_senhist/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_senhist.dir/build.make test/unittests/CMakeFiles/test_senhist.dir/build
.PHONY : test_senhist/fast

#=============================================================================
# Target rules for targets named test_reg_pkt_headergen

# Build rule for target.
test_reg_pkt_headergen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_reg_pkt_headergen
.PHONY : test_reg_pkt_headergen

# fast build rule for target.
test_reg_pkt_headergen/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_reg_pkt_headergen.dir/build.make test/unittests/CMakeFiles/test_reg_pkt_headergen.dir/build
.PHONY : test_reg_pkt_headergen/fast

#=============================================================================
# Target rules for targets named test_rechist

# Build rule for target.
test_rechist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_rechist
.PHONY : test_rechist

# fast build rule for target.
test_rechist/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_rechist.dir/build.make test/unittests/CMakeFiles/test_rechist.dir/build
.PHONY : test_rechist/fast

#=============================================================================
# Target rules for targets named test_qlog

# Build rule for target.
test_qlog: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_qlog
.PHONY : test_qlog

# fast build rule for target.
test_qlog/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_qlog.dir/build.make test/unittests/CMakeFiles/test_qlog.dir/build
.PHONY : test_qlog/fast

#=============================================================================
# Target rules for targets named test_h3_framing

# Build rule for target.
test_h3_framing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_h3_framing
.PHONY : test_h3_framing

# fast build rule for target.
test_h3_framing/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_h3_framing.dir/build.make test/unittests/CMakeFiles/test_h3_framing.dir/build
.PHONY : test_h3_framing/fast

#=============================================================================
# Target rules for targets named test_purga

# Build rule for target.
test_purga: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_purga
.PHONY : test_purga

# fast build rule for target.
test_purga/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_purga.dir/build.make test/unittests/CMakeFiles/test_purga.dir/build
.PHONY : test_purga/fast

#=============================================================================
# Target rules for targets named test_parse_packet_in

# Build rule for target.
test_parse_packet_in: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_parse_packet_in
.PHONY : test_parse_packet_in

# fast build rule for target.
test_parse_packet_in/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_parse_packet_in.dir/build.make test/unittests/CMakeFiles/test_parse_packet_in.dir/build
.PHONY : test_parse_packet_in/fast

#=============================================================================
# Target rules for targets named test_packno_len

# Build rule for target.
test_packno_len: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_packno_len
.PHONY : test_packno_len

# fast build rule for target.
test_packno_len/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_packno_len.dir/build.make test/unittests/CMakeFiles/test_packno_len.dir/build
.PHONY : test_packno_len/fast

#=============================================================================
# Target rules for targets named test_streamgen

# Build rule for target.
test_streamgen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_streamgen
.PHONY : test_streamgen

# fast build rule for target.
test_streamgen/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_streamgen.dir/build.make test/unittests/CMakeFiles/test_streamgen.dir/build
.PHONY : test_streamgen/fast

#=============================================================================
# Target rules for targets named test_frame_writer

# Build rule for target.
test_frame_writer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_frame_writer
.PHONY : test_frame_writer

# fast build rule for target.
test_frame_writer/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_frame_writer.dir/build.make test/unittests/CMakeFiles/test_frame_writer.dir/build
.PHONY : test_frame_writer/fast

#=============================================================================
# Target rules for targets named test_quic_be_floats

# Build rule for target.
test_quic_be_floats: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_quic_be_floats
.PHONY : test_quic_be_floats

# fast build rule for target.
test_quic_be_floats/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_quic_be_floats.dir/build.make test/unittests/CMakeFiles/test_quic_be_floats.dir/build
.PHONY : test_quic_be_floats/fast

#=============================================================================
# Target rules for targets named test_lsquic_hash

# Build rule for target.
test_lsquic_hash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_lsquic_hash
.PHONY : test_lsquic_hash

# fast build rule for target.
test_lsquic_hash/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_lsquic_hash.dir/build.make test/unittests/CMakeFiles/test_lsquic_hash.dir/build
.PHONY : test_lsquic_hash/fast

#=============================================================================
# Target rules for targets named test_send_headers

# Build rule for target.
test_send_headers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_send_headers
.PHONY : test_send_headers

# fast build rule for target.
test_send_headers/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_send_headers.dir/build.make test/unittests/CMakeFiles/test_send_headers.dir/build
.PHONY : test_send_headers/fast

#=============================================================================
# Target rules for targets named test_hcsi_reader

# Build rule for target.
test_hcsi_reader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hcsi_reader
.PHONY : test_hcsi_reader

# fast build rule for target.
test_hcsi_reader/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_hcsi_reader.dir/build.make test/unittests/CMakeFiles/test_hcsi_reader.dir/build
.PHONY : test_hcsi_reader/fast

#=============================================================================
# Target rules for targets named test_alt_svc_ver

# Build rule for target.
test_alt_svc_ver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_alt_svc_ver
.PHONY : test_alt_svc_ver

# fast build rule for target.
test_alt_svc_ver/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_alt_svc_ver.dir/build.make test/unittests/CMakeFiles/test_alt_svc_ver.dir/build
.PHONY : test_alt_svc_ver/fast

#=============================================================================
# Target rules for targets named test_frame_chop

# Build rule for target.
test_frame_chop: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_frame_chop
.PHONY : test_frame_chop

# fast build rule for target.
test_frame_chop/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_frame_chop.dir/build.make test/unittests/CMakeFiles/test_frame_chop.dir/build
.PHONY : test_frame_chop/fast

#=============================================================================
# Target rules for targets named test_rst_stream_gquic_be

# Build rule for target.
test_rst_stream_gquic_be: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_rst_stream_gquic_be
.PHONY : test_rst_stream_gquic_be

# fast build rule for target.
test_rst_stream_gquic_be/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_rst_stream_gquic_be.dir/build.make test/unittests/CMakeFiles/test_rst_stream_gquic_be.dir/build
.PHONY : test_rst_stream_gquic_be/fast

#=============================================================================
# Target rules for targets named test_export_key

# Build rule for target.
test_export_key: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_export_key
.PHONY : test_export_key

# fast build rule for target.
test_export_key/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_export_key.dir/build.make test/unittests/CMakeFiles/test_export_key.dir/build
.PHONY : test_export_key/fast

#=============================================================================
# Target rules for targets named test_trapa

# Build rule for target.
test_trapa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_trapa
.PHONY : test_trapa

# fast build rule for target.
test_trapa/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_trapa.dir/build.make test/unittests/CMakeFiles/test_trapa.dir/build
.PHONY : test_trapa/fast

#=============================================================================
# Target rules for targets named test_engine_ctor

# Build rule for target.
test_engine_ctor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_engine_ctor
.PHONY : test_engine_ctor

# fast build rule for target.
test_engine_ctor/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_engine_ctor.dir/build.make test/unittests/CMakeFiles/test_engine_ctor.dir/build
.PHONY : test_engine_ctor/fast

#=============================================================================
# Target rules for targets named test_ack

# Build rule for target.
test_ack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ack
.PHONY : test_ack

# fast build rule for target.
test_ack/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_ack.dir/build.make test/unittests/CMakeFiles/test_ack.dir/build
.PHONY : test_ack/fast

#=============================================================================
# Target rules for targets named test_di_nocopy

# Build rule for target.
test_di_nocopy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_di_nocopy
.PHONY : test_di_nocopy

# fast build rule for target.
test_di_nocopy/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_di_nocopy.dir/build.make test/unittests/CMakeFiles/test_di_nocopy.dir/build
.PHONY : test_di_nocopy/fast

#=============================================================================
# Target rules for targets named test_elision

# Build rule for target.
test_elision: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_elision
.PHONY : test_elision

# fast build rule for target.
test_elision/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_elision.dir/build.make test/unittests/CMakeFiles/test_elision.dir/build
.PHONY : test_elision/fast

#=============================================================================
# Target rules for targets named test_hkdf

# Build rule for target.
test_hkdf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hkdf
.PHONY : test_hkdf

# fast build rule for target.
test_hkdf/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_hkdf.dir/build.make test/unittests/CMakeFiles/test_hkdf.dir/build
.PHONY : test_hkdf/fast

#=============================================================================
# Target rules for targets named mini_parse

# Build rule for target.
mini_parse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mini_parse
.PHONY : mini_parse

# fast build rule for target.
mini_parse/fast:
	$(MAKE) -f test/unittests/CMakeFiles/mini_parse.dir/build.make test/unittests/CMakeFiles/mini_parse.dir/build
.PHONY : mini_parse/fast

#=============================================================================
# Target rules for targets named test_dec

# Build rule for target.
test_dec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_dec
.PHONY : test_dec

# fast build rule for target.
test_dec/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_dec.dir/build.make test/unittests/CMakeFiles/test_dec.dir/build
.PHONY : test_dec/fast

#=============================================================================
# Target rules for targets named test_cubic

# Build rule for target.
test_cubic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_cubic
.PHONY : test_cubic

# fast build rule for target.
test_cubic/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_cubic.dir/build.make test/unittests/CMakeFiles/test_cubic.dir/build
.PHONY : test_cubic/fast

#=============================================================================
# Target rules for targets named test_crypto_gen

# Build rule for target.
test_crypto_gen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_crypto_gen
.PHONY : test_crypto_gen

# fast build rule for target.
test_crypto_gen/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_crypto_gen.dir/build.make test/unittests/CMakeFiles/test_crypto_gen.dir/build
.PHONY : test_crypto_gen/fast

#=============================================================================
# Target rules for targets named test_alarmset

# Build rule for target.
test_alarmset: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_alarmset
.PHONY : test_alarmset

# fast build rule for target.
test_alarmset/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_alarmset.dir/build.make test/unittests/CMakeFiles/test_alarmset.dir/build
.PHONY : test_alarmset/fast

#=============================================================================
# Target rules for targets named test_conn_close_gquic_be

# Build rule for target.
test_conn_close_gquic_be: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_conn_close_gquic_be
.PHONY : test_conn_close_gquic_be

# fast build rule for target.
test_conn_close_gquic_be/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_conn_close_gquic_be.dir/build.make test/unittests/CMakeFiles/test_conn_close_gquic_be.dir/build
.PHONY : test_conn_close_gquic_be/fast

#=============================================================================
# Target rules for targets named test_attq

# Build rule for target.
test_attq: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_attq
.PHONY : test_attq

# fast build rule for target.
test_attq/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_attq.dir/build.make test/unittests/CMakeFiles/test_attq.dir/build
.PHONY : test_attq/fast

#=============================================================================
# Target rules for targets named test_rtt

# Build rule for target.
test_rtt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_rtt
.PHONY : test_rtt

# fast build rule for target.
test_rtt/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_rtt.dir/build.make test/unittests/CMakeFiles/test_rtt.dir/build
.PHONY : test_rtt/fast

#=============================================================================
# Target rules for targets named test_ackparse_ietf

# Build rule for target.
test_ackparse_ietf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ackparse_ietf
.PHONY : test_ackparse_ietf

# fast build rule for target.
test_ackparse_ietf/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_ackparse_ietf.dir/build.make test/unittests/CMakeFiles/test_ackparse_ietf.dir/build
.PHONY : test_ackparse_ietf/fast

#=============================================================================
# Target rules for targets named test_bw_sampler

# Build rule for target.
test_bw_sampler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_bw_sampler
.PHONY : test_bw_sampler

# fast build rule for target.
test_bw_sampler/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_bw_sampler.dir/build.make test/unittests/CMakeFiles/test_bw_sampler.dir/build
.PHONY : test_bw_sampler/fast

#=============================================================================
# Target rules for targets named test_frame_reader

# Build rule for target.
test_frame_reader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_frame_reader
.PHONY : test_frame_reader

# fast build rule for target.
test_frame_reader/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_frame_reader.dir/build.make test/unittests/CMakeFiles/test_frame_reader.dir/build
.PHONY : test_frame_reader/fast

#=============================================================================
# Target rules for targets named test_arr

# Build rule for target.
test_arr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_arr
.PHONY : test_arr

# fast build rule for target.
test_arr/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_arr.dir/build.make test/unittests/CMakeFiles/test_arr.dir/build
.PHONY : test_arr/fast

#=============================================================================
# Target rules for targets named test_varint

# Build rule for target.
test_varint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_varint
.PHONY : test_varint

# fast build rule for target.
test_varint/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_varint.dir/build.make test/unittests/CMakeFiles/test_varint.dir/build
.PHONY : test_varint/fast

#=============================================================================
# Target rules for targets named graph_cubic

# Build rule for target.
graph_cubic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graph_cubic
.PHONY : graph_cubic

# fast build rule for target.
graph_cubic/fast:
	$(MAKE) -f test/unittests/CMakeFiles/graph_cubic.dir/build.make test/unittests/CMakeFiles/graph_cubic.dir/build
.PHONY : graph_cubic/fast

#=============================================================================
# Target rules for targets named test_packet_out

# Build rule for target.
test_packet_out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_packet_out
.PHONY : test_packet_out

# fast build rule for target.
test_packet_out/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_packet_out.dir/build.make test/unittests/CMakeFiles/test_packet_out.dir/build
.PHONY : test_packet_out/fast

#=============================================================================
# Target rules for targets named test_ackgen_gquic_be

# Build rule for target.
test_ackgen_gquic_be: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ackgen_gquic_be
.PHONY : test_ackgen_gquic_be

# fast build rule for target.
test_ackgen_gquic_be/fast:
	$(MAKE) -f test/unittests/CMakeFiles/test_ackgen_gquic_be.dir/build.make test/unittests/CMakeFiles/test_ackgen_gquic_be.dir/build
.PHONY : test_ackgen_gquic_be/fast

test/http_client.o: test/http_client.c.o

.PHONY : test/http_client.o

# target to build an object file
test/http_client.c.o:
	$(MAKE) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/test/http_client.c.o
.PHONY : test/http_client.c.o

test/http_client.i: test/http_client.c.i

.PHONY : test/http_client.i

# target to preprocess a source file
test/http_client.c.i:
	$(MAKE) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/test/http_client.c.i
.PHONY : test/http_client.c.i

test/http_client.s: test/http_client.c.s

.PHONY : test/http_client.s

# target to generate assembly for a file
test/http_client.c.s:
	$(MAKE) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/test/http_client.c.s
.PHONY : test/http_client.c.s

test/prog.o: test/prog.c.o

.PHONY : test/prog.o

# target to build an object file
test/prog.c.o:
	$(MAKE) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/test/prog.c.o
.PHONY : test/prog.c.o

test/prog.i: test/prog.c.i

.PHONY : test/prog.i

# target to preprocess a source file
test/prog.c.i:
	$(MAKE) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/test/prog.c.i
.PHONY : test/prog.c.i

test/prog.s: test/prog.c.s

.PHONY : test/prog.s

# target to generate assembly for a file
test/prog.c.s:
	$(MAKE) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/test/prog.c.s
.PHONY : test/prog.c.s

test/test_cert.o: test/test_cert.c.o

.PHONY : test/test_cert.o

# target to build an object file
test/test_cert.c.o:
	$(MAKE) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/test/test_cert.c.o
.PHONY : test/test_cert.c.o

test/test_cert.i: test/test_cert.c.i

.PHONY : test/test_cert.i

# target to preprocess a source file
test/test_cert.c.i:
	$(MAKE) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/test/test_cert.c.i
.PHONY : test/test_cert.c.i

test/test_cert.s: test/test_cert.c.s

.PHONY : test/test_cert.s

# target to generate assembly for a file
test/test_cert.c.s:
	$(MAKE) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/test/test_cert.c.s
.PHONY : test/test_cert.c.s

test/test_common.o: test/test_common.c.o

.PHONY : test/test_common.o

# target to build an object file
test/test_common.c.o:
	$(MAKE) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/test/test_common.c.o
.PHONY : test/test_common.c.o

test/test_common.i: test/test_common.c.i

.PHONY : test/test_common.i

# target to preprocess a source file
test/test_common.c.i:
	$(MAKE) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/test/test_common.c.i
.PHONY : test/test_common.c.i

test/test_common.s: test/test_common.c.s

.PHONY : test/test_common.s

# target to generate assembly for a file
test/test_common.c.s:
	$(MAKE) -f CMakeFiles/http_client.dir/build.make CMakeFiles/http_client.dir/test/test_common.c.s
.PHONY : test/test_common.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... docs"
	@echo "... http_client"
	@echo "... lsquic"
	@echo "... test_malo_pooled"
	@echo "... test_min_heap"
	@echo "... test_stream"
	@echo "... test_ack_merge"
	@echo "... test_wuf_gquic_be"
	@echo "... test_ver_nego"
	@echo "... test_minmax"
	@echo "... test_sfcw"
	@echo "... test_goaway_gquic_be"
	@echo "... test_streamparse"
	@echo "... test_spi"
	@echo "... test_ackparse_gquic_be"
	@echo "... test_shi"
	@echo "... test_blocked_gquic_be"
	@echo "... test_stop_waiting_gquic_be"
	@echo "... test_set"
	@echo "... test_malo_nopool"
	@echo "... test_senhist"
	@echo "... test_reg_pkt_headergen"
	@echo "... test_rechist"
	@echo "... test_qlog"
	@echo "... test_h3_framing"
	@echo "... test_purga"
	@echo "... test_parse_packet_in"
	@echo "... test_packno_len"
	@echo "... test_streamgen"
	@echo "... test_frame_writer"
	@echo "... test_quic_be_floats"
	@echo "... test_lsquic_hash"
	@echo "... test_send_headers"
	@echo "... test_hcsi_reader"
	@echo "... test_alt_svc_ver"
	@echo "... test_frame_chop"
	@echo "... test_rst_stream_gquic_be"
	@echo "... test_export_key"
	@echo "... test_trapa"
	@echo "... test_engine_ctor"
	@echo "... test_ack"
	@echo "... test_di_nocopy"
	@echo "... test_elision"
	@echo "... test_hkdf"
	@echo "... mini_parse"
	@echo "... test_dec"
	@echo "... test_cubic"
	@echo "... test_crypto_gen"
	@echo "... test_alarmset"
	@echo "... test_conn_close_gquic_be"
	@echo "... test_attq"
	@echo "... test_rtt"
	@echo "... test_ackparse_ietf"
	@echo "... test_bw_sampler"
	@echo "... test_frame_reader"
	@echo "... test_arr"
	@echo "... test_varint"
	@echo "... graph_cubic"
	@echo "... test_packet_out"
	@echo "... test_ackgen_gquic_be"
	@echo "... test/http_client.o"
	@echo "... test/http_client.i"
	@echo "... test/http_client.s"
	@echo "... test/prog.o"
	@echo "... test/prog.i"
	@echo "... test/prog.s"
	@echo "... test/test_cert.o"
	@echo "... test/test_cert.i"
	@echo "... test/test_cert.s"
	@echo "... test/test_common.o"
	@echo "... test/test_common.i"
	@echo "... test/test_common.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

